import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import { cn } from "@/lib/utils";

import { Inter as FontSans } from "next/font/google";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Pokemon Showcase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <main className="container max-w-5xl mx-auto px-4 md:px-10 xl:px-0 pb-10">
          <nav className="border mb-10 flex justify-between p-5">
            <h3 className="font-bold text-xl">Pokemons Showcase</h3>

            <ul>
              <Link href="/" className="hover:underline">
                Back to list
              </Link>
            </ul>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
